# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cpu.xdc

# IP: ip/my_ram/my_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==my_ram || ORIG_REF_NAME==my_ram} -quiet] -quiet

# IP: ip/my_rom/my_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==my_rom || ORIG_REF_NAME==my_rom} -quiet] -quiet

# XDC: f:/vivado_workspace/mycpu1/mycpu1.gen/sources_1/ip/my_ram/my_ram_ooc.xdc

# XDC: f:/vivado_workspace/mycpu1/mycpu1.gen/sources_1/ip/my_rom/my_rom_ooc.xdc
